services:
  calculator:
    build: App_practical/17_Calculator/
    ports:
      - "5217:5017"
    environment:
      ASPNETCORE_URLS: "http://+:5017"
    networks:
      - metrics-net-17



  prometheus:
    image: prom/prometheus:latest
    user: root
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9217:9090"
    networks:
      - metrics-net-17

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - "5067:8081"
    networks:
      - metrics-net-17

  grafana:
    image: grafana/grafana:latest
    user: root
    depends_on:
      - prometheus
      - renderer
    ports:
      - "3017:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    networks:
      - metrics-net-17

networks:
  metrics-net-17:
    name: metrics-net-17
