services:
  mariadb:
    container_name: web-mariadb-17
    hostname: mariadb
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: 17_WebCalculatorDb
      MARIADB_USER: webuser
      MARIADB_PASSWORD: password
    ports:
      - "5037:3306"

      
  web:
    container_name: web-app-calculator-17
    hostname: app
    build: 17_Calculator/

    ports:
      - "0.0.0.0:5017:5017"

